### ISSUE TITLE
Need hlep

### ISSUE THREAD

**Issue by D4RK009** [deikaze16/mikeydoc2#2]
Bro can you send me your discord user and tag so i can contact you i have issue
when I click on link called local say
 Hmmm… can't reach this pagelocalhost refused to connect.
Try:

Search the web for [localhost](https://www.bing.com/search?form=ANLKDR&q=localhost)
Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)

**Comment by deikaze16** [comment]
Dei#4445. anyway, this project is discontinued.

**Comment by D4RK009** [comment]
So this project will not work?
